[package]
name = "industrial-relay-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core async - no hardware dependencies
embassy-executor = "0.5.0"
embassy-time = "0.3.0"
embassy-sync = "0.5.0"

# Logging
defmt = "0.3.0"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }

# For simulation
cortex-m = "0.7.7"