[package]
name = "esp32-relay-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
esp32-hal = "0.15.0"
embedded-hal = "1.0.0"

# Async runtime
embassy-executor = "0.5.0"
embassy-time = "0.3.0"
embassy-sync = "0.5.0"

# Logging
defmt = "0.3.0"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }