[package]
name = "esp32-module-industrial"
version = "0.1.0"
edition = "2021"

[dependencies]
# ESP32 HAL
esp32-hal = "0.15.0"
embedded-hal = "1.0.0"

# Async runtime
embassy-executor = { version = "0.5.0", features = ["arch-xtensa", "executor-thread", "integrated-timers"] }
embassy-time = "0.3.0"
embassy-sync = "0.5.0"

# Logging
defmt = "0.3.0"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }